name: Build

on:
  - push
  - pull_request

permissions:
  contents: write

jobs:
  build_plugin:
    name: Build Plugin
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Download Decky CLI
        run: |
          mkdir /tmp/decky-cli
          curl -L -o /tmp/decky-cli/decky "https://github.com/SteamDeckHomebrew/cli/releases/download/0.0.7/decky-linux-x86_64"
          chmod +x /tmp/decky-cli/decky

          echo "/tmp/decky-cli" >> $GITHUB_PATH

      - name: Build plugins
        run: |
          # Run the CLI as root to get around Docker's weird permissions
          sudo $(which decky) plugin build -b -o /tmp/output
          sudo chown -R $(whoami) .

      - name: Upload Artifacts to Github
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: /tmp/output/*.zip


  publish:
    name: Publish release
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: build_plugin
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: .

      - name: Publish to Github release
        uses: softprops/action-gh-release@v2
        with:
          files: ./artifacts/*
          name: Release ${{ github.ref_name }}
          draft: false
          generate_release_notes: true
          prerelease: ${{ contains(github.ref, 'pre') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
